SELECT  SNAME
FROM SUPPLIER, SUPPLY
WHERE SUPPLIER.S# = SUPPLY.S#
AND SUPPLY.P# = 'P2';
--
SELECT JNAME
FROM PROJECT
WHERE J# IN (SELECT P# 
FROM SUPPLY
WHERE P# = 'P2');

-- join: 
SELECT T.SNAME
FROM SUPPLIER T
JOIN SUPPLY S
ON T.S# = S.S# 
WHERE S.P# = 'P2';

--
SELECT SNAME
FROM SUPPLIER
WHERE S# IN (SELECT S#
FROM SUPPLY
WHERE P# = 'P2'); 

-- Q3 v1
SELECT PROJECT.JNAME
--,SUPPLY.J#
--,SUPPLY.P#
FROM PROJECT, SUPPLY
WHERE PROJECT.J# = SUPPLY.J#
AND P# = 'P2'
ORDER BY JNAME ASC;

-- Q3 v2
SELECT JNAME 
FROM PROJECT 
WHERE J# IN (SELECT J#
FROM SUPPLY
WHERE P# = 'P2')
ORDER BY JNAME ASC;

--Q4 v1
SELECT DISTINCT SUPPLY.P#
FROM SUPPLY, SUPPLIER, PROJECT
WHERE PROJECT.CITY = 'ATHENS'
ORDER BY SUPPLY.P# ASC;

--Q4 v2
SELECT DISTINCT P# 
FROM SUPPLY
WHERE J# IN (SELECT J#
FROM PROJECT 
WHERE CITY = 'ATHENS')
ORDER BY P# ASC;

--Q5 a
SELECT DISTINCT J#
FROM SUPPLY
WHERE P# IN (SELECT P#
FROM PART
WHERE WEIGHT < 14)
ORDER BY J# ASC;

--Q5 b

SELECT DISTINCT j.JNAME
, j.J#
FROM PROJECT j, SUPPLY s, SUPPLIER p
WHERE j.J# = s.J#
AND P# IN (SELECT P#
FROM PART
WHERE WEIGHT < 14)
ORDER BY j.J# ASC;

--Q6


SELECT DISTINCT PROJECT.J#
, PROJECT.JNAME
, PART.P# 
, PART.PNAME
FROM PROJECT, SUPPLY, PART
WHERE PROJECT.J# = SUPPLY.J#
AND PART.P# = SUPPLY.P#
AND PART.COLOUR = 'BLUE'
ORDER BY J# DESC









